apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-products
  template:
    metadata:
      labels:
        app: prod-products
    spec:
      containers:
        - name: prod-products
          image: 218266829911.dkr.ecr.us-east-1.amazonaws.com/prod-products:latest
          ports:
            - containerPort: 8080
