apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-orders-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-orders
  template:
    metadata:
      labels:
        app: prod-orders
    spec:
      containers:
        - name: prod-orders
          image: 218266829911.dkr.ecr.us-east-1.amazonaws.com/prod-orders:latest
          ports:
            - containerPort: 6500
          env:
            - name: PAYMENTS_SERVICE_URL
              value: "http://backend-payments-service.default.svc.cluster.local:80"
            - name: SHIPPING_SERVICE_URL
              value: "http://backend-shipping-service.default.svc.cluster.local:80"
            - name: PRODUCTS_SERVICE_URL
              value: "http://backend-products-service.default.svc.cluster.local:80"

