apiVersion: v1
kind: Service
metadata:
  name: dev-products-service
spec:
  selector:
    app: dev-products
  ports:
    - protocol: TCP
      port: 80           # Puerto externo al que se conecta
      targetPort: 7000    # Puerto al que se conecta el contenedor
  type: LoadBalancer      # Crea un Load Balancer en AWS