apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-orders-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-orders
  template:
    metadata:
      labels:
        app: dev-orders
    spec:
      containers:
        - name: dev-orders
          image: 218266829911.dkr.ecr.us-east-1.amazonaws.com/dev-orders:latest
          ports:
            - containerPort: 6500
          env:
            - name: PAYMENTS_SERVICE_URL
              value: "http://dev-backend-payments-service.default.svc.cluster.local:5000"
            - name: SHIPPING_SERVICE_URL
              value: "http://dev-backend-shipping-service.default.svc.cluster.local:6000"
            - name: PRODUCTS_SERVICE_URL
              value: "http://dev-backend-products-service.default.svc.cluster.local:7000"